name: Context testing
on: push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
  context:
    runs-on: ubuntu-latest
    steps:
      - name: context test
        run: |
          echo "github.pusher: ${{ github.event.pusher }}"
          echo "toJSON github.pusher: ${{ toJSON(github.event.pusher) }}"
          echo "runner.os: ${{ runner.os }}"
    
