name: Shell Commands

on: push

jobs:
  run-shell-command:
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: singleline script
        run: >
          echo "This is 
          single line"
